# 异步任务解决方案

JavaScript语言的执行环境是单线程。即一次只能完成一个任务。若有多个任务则需排队逐个执行——前一个任务完成，再执行后一个任务。

这种执行模式实现简单，执行环境相对单纯。但随着前端业务日渐复杂，事务和请求等日渐增多，这种单线程执行方式在复杂的业务下势必效率低下，只要有一个任务耗时很长，后面的任务都必须排队等着，会拖延整个程序的执行。常见的浏览器无响应（假死），往往就是因为某一段JavaScript代码长时间运行（比如死循环），导致整个页面卡在这个地方，其他任务无法执行。

为避免和解决这种问题，JavaScript语言将任务执行模式分为异步和同步。同步模式”就是上一段的模式，后一个任务等待前一个任务结束，然后再执行，程序的执行顺序与任务的排列顺序是一致的、同步的；”异步模式”则完全不同，每一个任务有一个或多个回调函数（callback），前一个任务结束后，不是执行后一个任务，而是执行回调函数，后一个任务则是不等前一个任务结束就执行，所以程序的执行顺序与任务的排列顺序是不一致的、异步的。

# 回调函数

异步编程最基本方法。

回调函数的英文定义：A callback is a function that is passed as an argument to  another function and is executed after its parent function has  completed。

字面上的理解，回调函数就是一个参数，将这个函数作为参数传到另一个函数里面，当那个函数执行完之后，再执行传进去的这个函数。这个过程就叫做回调。

举例使用场景：

- ajax请求

- DOM事件是基于回调机制

- setTimeout、setInterval

回调函数这种方式的优点是比较容易理解，缺点是回调过多时，运行流程会变得很不清晰。

例如：首先假设要渲染一个页面，只能异步的串行请求A，B，C，然后才能拿到页面的数据并请求页面。这时，利用回调会实现如下：

```js
// 假设request是一个异步函数
request(A, function (data) {
  
    request(B, function () {
      
        request(C, function () {
          
            // 渲染页面
        })
    })
})
```

回调函数的嵌套是愈发深入的。在不断的回调中，request(A)回调函数中的其他逻辑会影响到request(B)，request(C)中的逻辑，同理，request(B)中的其他逻辑也会影响到request(C)。在这个例子中，request(A)调用request(B)，request(B)调用request(C)，request(C)执行完毕返回，request(B)执行完毕返回，request(A)执行完毕返回。我们很快会对先后顺序产生混乱，从而很难直观的分析出异步回调的结果。这就被称为**回调地狱。**

随着ES6标准的发布，处理异步数据流的解决方案又有了新的变化。promise就是这其中的一个。我们都知道，在传统的ajax请求中，当异步请求之间的数据存在依赖关系的时候，就可能产生很难看的多层回调，这样会使代码逻辑很容易造成混乱不便于阅读和后期维护，俗称”回调地狱”（callback  hell）。另一方面，往往错误处理的代码和正常的业务代码耦合在一起，造成代码会极其难看。为了让编程更美好，我们就需要引入`promise`来降低异步编程的复杂性。

所以某种程度上说，**promise是对上面说到的回调函数处理异步编程的一个进阶方案。**首先Promise是CommandJS 提出的一种规范，其目的是为异步编程提供统一接口。

简单说，**Promise的思想是，每一个异步任务返回一个Promise对象，该对象有一个then方法，允许指定回调函数。**

```js
// 假设request是一个Promise函数
request(A)
  .then(function (data) {
  
    return request(B)
	})
  .then(function () {
  	
    return request(C)
	})
  .then(function () {
    // 渲染页面
	})
  .catch(function(){
    //错误处理
	})
```

Promise对象用then函数来指定回调。所以，之前在回调函数的例子可以改为上文中的模样。可以看到，Promise并没有消除回调地狱，但是却通过then链将代码逻辑变得更加清晰了。在这个例子中，request(A)调用request(B)，request(B)调用request(C)，request(C)执行完毕返回。

# Promise(ES2015)

Promise是ES6的一个新类型，是一种新的异步任务解决方案。Promise，含义是承诺。Promise构造函数的参数是一个函数，函数有两个参数，resolve,reject；这两个参数也是promise的函数，resolve的作用是修改任务状态为成功，同时传递任务结果数据；reject的作用是修改任务状态为失败，同时传递失败原因。

```JS
const promise = new Promise((resolve, reject) => {
  $.get('https://github.com/users').success((res) =>  {
    resolve(res);
  }).fail((err) => {
    reject(err);
  });
});

promise.then((value) => {
  console.log(value);
},(err) => {
  console.log(err);
});
//也可以采取下面这种写法
promise.then(value => {
	console.log(value)
}).catch(err => {
	console.log(err)
});
```

上面的例子，会在Ajax请求成功后调用`resolve`回调函数来处理结果，如果请求失败则调用`reject`回调函数来处理错误。**Promise对象内部包含三种状态，分别为pending,fulfilled和rejected。**这三种状态可以类比于我们平常在ajax数据请求过程的pending,success,error。**一开始异步任务时，状态是Pending,表示正在等待处理完毕，这个状态是中间状态而且是单向不可逆的。成功获得值后状态就变为fulfilled，然后将成功获取到的值存储起来，后续可以通过调用`then`方法传入的回调函数来进一步处理。而如果失败了的话，状态变为rejected,错误可以选择抛出（throw)或者调用`reject`方法来处理。**

任务的几个状态：

- pending（中间状态）—> fulfilled , rejected

- fulfilled（最终态）—> 返回value 不可变 ；通过resolve方法修改任务状态为成功

- rejected（最终态） —> 返回reason 不可变，通过reject方法修改任务状态为失败

## Promise的实例方法

​	**then**：then是为 Promise 实例添加状态改变时的回调函数。then方法的第一个参数是resolved状态的回调函数，第二个参数（可选）是rejected状态的回调函数。**then方法返回的是一个新的Promise实例**（注意，不是原来那个Promise实例）。因此可以**采用链式写法**，即then方法后面再调用另一个then方法。

​	**catch**：catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数。

## Promise的类（静态）方法

**Promise.all(iterator)**:参数是一个数组，数组中每一个元素是promise对象；返回一个新的`promise`对象；其中所有promise的对象均成功触发时，该对象才会触发成功，若有任何一个发生错误，就会触发该对象的失败方法。成功触发的返回值是所有promise对象返回值组成的数组。

```js
//设置三个任务
const tasks = {
  task1() {
    return new Promise(...); //return 1
  },
  
  task2() {
    return new Promise(...); // return 2
  },
  
  task3() {
    return new Promise(...); // return 3
  }
};

//列表中的所有任务会并发执行，当所有任务执行状态都为fulfilled后，执行then方法
Promise.all([tasks.task1(), tasks.task2(), tasks.task3()]).then(result => console.log(result));
//最终结果为：[1,2,3]
```

例如：小程序云开发中，云函数中，一次读取数据库集合中所有数据。

**Promise.race(iterable)**: 返回一个新的`promise`对象，其回调函数迭代遍历每个值，分别处理。同样都是传入一组promise对象进行处理，同Promise.all不同的是，只要其中有一个promise的状态变为`fulfilled`或`rejected`，就会调用后续的操作。

```js
//设置三个任务
const tasks = {
  task1() {
    return new Promise(...); //return 1
  },
  
  task2() {
    return new Promise(...); // return 2
  },
  
  task3() {
    return new Promise(...); // return 3
  }
};

//列表中的所有任务会并发执行，只要有一个promise对象出现结果，就会执行then方法
Promise.race([tasks.task1(), tasks.task2(), tasks.task3()]).then(result => console.log(result));
//假设任务1最开始返回结果，则控制台打印结果为`1`
```

# Async/Await(ES2017)

- async/await是写异步代码的新方式，以前的方法有**回调函数**和**Promise**。
- async/await是**基于Promise实现**的，它不能用于普通的回调函数。
- async/await与Promise一样，是非阻塞的。
- **async/await使得异步代码看起来像同步代码，这正是它的魔力所在。**

`async/await`实际上是`Generator`的语法糖。顾名思义，**async关键字代表后面的函数中有异步操作，`await`表示等待一个异步方法执行完成**。声明异步函数只需在普通函数前面加一个关键字`async`即可，如：

```js
async function funcA() {}
```

**async函数返回一个Promise对象**（如果指定的返回值不是Promise对象，也返回一个Promise，只不过立即 `resolve `，处理方式同 `then `方法），因此 `async `函数通过 `return `返回的值，会成为 `then `方法中回调函数的参数：

```
async function funcA() {
  return 'hello!';
}

funcA().then(value => {
  console.log(value);
})
// hello!
```

单独一个 `async `函数，其实与Promise执行的功能是一样的，来看看 `await `都干了些啥。

顾名思义， **await  就是异步等待，它等待的是一个Promise，因此 `await `后面应该写一个Promise对象，如果不是Promise对象，那么会被转成一个立即 `resolve `的Promise**。 **async 函数被调用后就立即执行，但是一旦遇到 `await `就会先返回，等到异步操作执行完成，再接着执行函数体内后面的语句。**总结一下就是：`async`函数调用不会造成代码的阻塞，但是`await`会引起`async`函数内部代码的阻塞。看看下面这个例子：

```js
async function func() {
  console.log('async function is running!  1 ');
  const num1 = await 200;
  console.log(`num1 is ${num1} 2 `);
  const num2 = await num1+ 100;
  console.log(`num2 is ${num2} 3 `);
  const num3 = await num2 + 100;
  console.log(`num3 is ${num3} 4 `);
}

func();
console.log('run me before await! 5 ')；
console.log("6")；

// async function is running!
// run me before await!
// num1 is 200
// num2 is 300
// num3 is 400
```

可以看出调用 `async func` 函数后，它会立即执行，首先输出了`'async function is running!'`，接着遇到了 `await `异步等待，函数返回，先执行`func()`后面的同步任务，同步任务执行完后，接着await等待的位置继续往下执行。可以说，`async`函数完全可以看作多个异步操作，包装成的一个Promise 对象，而`await`命令就是内部`then`命令的语法糖。

值得注意的是， `await ` 后面的 Promise 对象不总是返回 ` resolved  `状态，只要一个 `await `后面的Promise状态变为 `rejected `，整个 `async `函数都会中断执行，为了保存错误的位置和错误信息，我们需要用 `try...catch` 语句来封装多个 `await `过程，如下：

```js
async function func() {
  try {
    const num1 = await 200;
    console.log(`num1 is ${num1}`);
    const num2 = await Promise.reject('num2 is wrong!');
    console.log(`num2 is ${num2}`);
    const num3 = await num2 + 100;
    console.log(`num3 is ${num3}`);
  } catch (error) {
    console.log(error);
  }
}

func();
// num1 is 200
// 出错了
// num2 is wrong!
```

如上所示，在 `num2 `处 `await `得到了一个状态为 `rejected `的Promise对象，该错误会被传递到 `catch `语句中，这样我们就可以定位错误发生的位置。

```js
async function onLoad(){
  try {
    this.list = await axios.get("url");
  } catch (error) {
  	console.log(error);
  }
}
```

